language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gae-rest' ]; then cd .. && eval "mv $currentfolder generator-gae-rest" && cd generator-gae-rest; fi

